### ISSUE TITLE
Form dissapears on post when no data submitted

### ISSUE THREAD

**Issue by photoman** [BigBlockStudios/modMailchimp#16]
Same issue as this post: http://forums.modx.com/forums/thread/79411/modmailchimp#dis-post-437428

When nothing is filled out in the form and it is submitted - the Lexicon error message appears but the form disappears - leaving no way to resubmit the data or fill out the form.

Please fix!!
Thank you.

![screen shot 2013-09-04 at 6 43 36 pm](https://f.cloud.github.com/assets/1184507/1084654/8129b088-15b3-11e3-8b63-6e248950d74b.png)

![screen shot 2013-09-04 at 6 20 23 pm](https://f.cloud.github.com/assets/1184507/1084653/7b721234-15b3-11e3-8057-4721b44b8034.png)

**Comment by di5abled** [comment]
Hello,

this Error still exists.

will you fix this? 
or can you give me a hint where to look in the code to fix this behavior?

mailchimp errors are displayed correctly, but your "custom errors" are just showing the error and no formular.

**Comment by BigBlockStudios** [comment]
modMailchimp is no longer being maintained,  we are looking for maintainers to take over the project.
